import Foundation

enum BuildingType: String, Codable {
    case special = "Special"
    case fluidProduction = "Fluid Production"
    case manufacturers = "Manufacturers"
    case miners = "Miners"
    case smelters = "Smelters"
    case workstations = "Workstations"
    case generators = "Generators"
    case powerPoles = "Power Poles"
    case wallPoles = "Wall Poles"
    case conveyorBelts = "Conveyor Belts"
    case conveyorLifts = "Conveyor Lifts"
    case conveyorSupports = "Conveyor Supports"
    case pipeSupports = "Pipe Supports"
    case pipelines = "Pipelines"
    case sorting = "Sorting"
    case storage = "Storage"
    case towers = "Towers"
    case walkways = "Walkways"
    case conveyorConnections = "Conveyor Connections"
    case walls = "Walls"
    case foundations = "Foundations"
    case ramps = "Ramps"
    case hypertubes = "Hypertubes"
    case jumpPads = "Jump Pads"
    case motorVehicles = "Motor Vehicles"
}
