import Foundation

enum PartTypeLegacy: String, Codable {
    case hubParts = "Hub Parts"
    case ores = "Ores"
    case fuels = "Fuels"
    case aliens = "Aliens"
    case powerSlugs = "Power Slugs"
    case liquids = "Liquids"
    case gases = "Gases"
    case ingots = "Ingots"
    case standartParts = "Standart Parts"
    case electronics = "Electronics"
    case minerals = "Minerals"
    case biomass = "Biomass"
    case powerShards = "Power Shards"
    case industrialParts = "Industrial Parts"
    case consumed = "Consumed"
    case communications = "Communications"
    case containers = "Containers"
    case oilProducts = "Oil Products"
    case nuclear = "Nuclear"
    case spaceElevatorParts = "Space Elevator Parts"
    case ficsmas = "FICSMAS"
}
